apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: homework
  name: nginx-deployment
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  replicas: 3
  template:
    metadata:
      name: nginx-deployment
      labels:
        app: nginx
    spec:
      nodeSelector:
        homework: "true"
      initContainers:
      - name: init
        image: busybox
        command: ['sh', '-c', 'echo "Hello!" > /init/index.html']
        volumeMounts:
        - name: shared-volumes
          mountPath: "/init"
      containers:
      - name: nginx
        image: nginx:1.25-alpine3.18
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: shared-volumes
          mountPath: /homework
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh","-c","rm -f /homework/index.html"]
        readinessProbe:
          exec:
            command:
            - cat
            - /homework/index.html
          initialDelaySeconds: 5       
          periodSeconds: 5       
      volumes:
      - name: shared-volumes
        emptyDir: {}